OBS build, enable Debian ARM builds

diff --git a/builds/linux/obs/debian/rules b/builds/linux/obs/debian/rules
--- a/builds/linux/obs/debian/rules
+++ b/builds/linux/obs/debian/rules
@@ -1,6 +1,6 @@
 #!/usr/bin/make -f
 # -*- makefile -*-
-# Last Update October 09, 2020
+# Last Update October 10, 2020
 # Copyright 2017-2020 Trevor SANDY
 
 # output every command that modifies files on the build system.
@@ -12,17 +12,26 @@ export QT_SELECT=qt5
 # for 3rd party apps install
 export LP3D_BUILD_PKG=yes
 
-# get CPU arch
-export TARGET_CPU=`uname -m`
+# get CPU arch - returns arm for armv7l or arm64 for aarch64
+export TARGET_CPU=${DEB_BUILD_ARCH}
 
 # get OS name
-export TARGET_VENDOR=`. /etc/os-release 2>/dev/null; [ -n "$ID" ] && echo $ID || echo $OS_NAME | awk '{print tolower($0)}'`
+export TARGET_VENDOR := $(shell . /etc/os-release 2>/dev/null; [ -n "$${ID}" ] && echo "$${ID}" || echo 'undefined')
 
 # get OS version
-export PLATFORM_VER=`. /etc/os-release 2>/dev/null; [ -n "$VERSION_ID" ] && echo $VERSION_ID || echo 'undefined'`
+export PLATFORM_VER := $(shell . /etc/os-release 2>/dev/null; [ -n "$${VERSION_ID}" ] && echo "$${VERSION_ID}" || echo 'undefined')
 
 # get app version suffix
-VER_SUFFIX=`cat builds/utilities/version.info | cut -d " " -f 1-2 | sed s/" "//g`
+LP3D_VER_SUFFIX := $(shell cat builds/utilities/version.info | cut -d " " -f 1-2 | sed s/" "//g)
+
+# get release directory name
+LP3D_RELEASE_DIR := $(shell [ ${TARGET_CPU} = x86_64 ] || [ ${TARGET_CPU} = aarch64 ] || [ ${TARGET_CPU} = arm64 ] && echo "64bit_release" || echo "32bit_release")
+
+# get lpub3d executable path
+LP3D_VALID_EXE := $(shell echo "mainApp/${LP3D_RELEASE_DIR}/lpub3d${LP3D_VER_SUFFIX}")
+
+# set compatibility level - does freaky stuff so disabled until I figure out what the hell is going on
+#export DH_COMPAT := $(shell [ ${PLATFORM_VER} = 10 ] && echo 10 || echo 9)
 
 %:
 	dh $@
@@ -71,9 +80,7 @@ configure-stamp:
 	export WD=$$(readlink -e ../); \
 	chmod +x builds/utilities/CreateRenderers.sh && ./builds/utilities/CreateRenderers.sh
 override_dh_auto_configure:
-	echo Platform ID.......$TARGET_VENDOR
-	echo Platform Version..$PLATFORM_VER
-	# LDraw directory - for build check
+	# Set LDraw directory for build check, and run qmake
 	export LDRAWDIR=${HOME}/ldraw; \
 	if which qmake >/dev/null 2>/dev/null ; then \
 		qmake -v; \
@@ -87,12 +94,8 @@ override_dh_auto_configure:
 build: configure-stamp
 override_dh_auto_test:
 	# Start custom test commands
-	lp3dRelease="32bit_release" && [ ${TARGET_CPU} = x86_64 ] || [ ${TARGET_CPU} = aarch64 ] && lp3dRelease="64bit_release"
-	echo ReleaseArch.......$${lp3dRelease}
-	echo VersionSuffix.....${VER_SUFFIX}
-	#validExe="mainApp/$${lp3dRelease}/lpub3d${VER_SUFFIX}"
-	#[ -f "$${validExe}" ] && echo "LDD check lpub3d${VER_SUFFIX}..." && ldd $${validExe} 2>/dev/null || \
-	#echo "ERROR - LDD check failed for $$(realpath $${validExe})"
+	[ -f "${LP3D_VALID_EXE}" ] && echo "LDD check lpub3d${LP3D_VER_SUFFIX}..." && ldd ${LP3D_VALID_EXE} 2>/dev/null || \
+	echo "ERROR - LDD check failed for $$(realpath ${LP3D_VALID_EXE})"
 	# End custom test commands
 	dh_auto_test
 
@@ -111,3 +114,4 @@ clean:
 override_dh_strip_nondeterminism:
 
 .PHONY: configure build clean
+
